version: '3'
vars:
  VERSION:
    sh: cat VERSION
  BUILD_DIR: build
  # Default variables for remote Mac tasks. Override with CLI vars.
  # e.g. task macos:build MAC_HOST=user@192.168.1.50
  MAC_HOST: '{{.MAC_HOST | default "user@remote-mac"}}'
  MAC_API_HOST: '{{.MAC_API_HOST | default "remote-mac"}}'
  MAC_API_PORT: '{{.MAC_API_PORT | default "8089"}}'

tasks:
  default:
    cmds:
      - task --list

  # ============================================================================
  # BUILD & RUN
  # ============================================================================

  build:
    desc: Build both server and client binaries
    deps: [build-server, build-client]

  build-server:
    desc: Build the server binary
    cmds:
      - mkdir -p {{.BUILD_DIR}}
      - go build -ldflags="-s -w -X upscale-service/internal/version.Version={{.VERSION}}" -o {{.BUILD_DIR}}/upscale-server ./cmd/server
    sources:
      - cmd/server/**/*.go
      - internal/**/*.go
    generates:
      - '{{.BUILD_DIR}}/upscale-server'

  build-client:
    desc: Build the client binary
    cmds:
      - mkdir -p {{.BUILD_DIR}}
      - go build -ldflags="-s -w -X upscale-service/internal/version.Version={{.VERSION}}" -o {{.BUILD_DIR}}/upscale-client ./cmd/client
    sources:
      - cmd/client/**/*.go
      - internal/**/*.go
    generates:
      - '{{.BUILD_DIR}}/upscale-client'

  run:
    desc: Run the server locally
    deps: [build-server]
    cmds:
      - ./{{.BUILD_DIR}}/upscale-server

  clean:
    desc: Remove build artifacts and temporary files
    cmds:
      - rm -rf {{.BUILD_DIR}}
      - rm -f test_upscaled.png test_output.png
      - rm -rf test/testdata/sample_images/test.png

  models:
    desc: Download the Real-ESRGAN models
    cmds:
      - ./scripts/download-models.sh

  # ============================================================================
  # DOCKER
  # ============================================================================

  docker-build:
    desc: Build the Docker image
    cmds:
      - docker build -t upscale-service:latest -f deployments/docker/Dockerfile .

  docker-run:
    desc: Run the service using Docker Compose
    cmds:
      - docker compose -f deployments/docker/docker-compose.yml up -d --build

  docker-stop:
    desc: Stop the Docker Compose service
    cmds:
      - docker compose -f deployments/docker/docker-compose.yml down

  docker-logs:
    desc: View service logs
    cmds:
      - docker compose -f deployments/docker/docker-compose.yml logs -f

  # ============================================================================
  # TESTING
  # ============================================================================

  test:
    desc: Run unit tests
    cmds:
      - go test -v ./internal/...

  test-integration:
    desc: Run integration tests (requires server running on port 8089)
    cmds:
      - ./test/integration/test_api.sh

  # ============================================================================
  # MACOS REMOTE
  # ============================================================================

  build-macos-app:
    desc: Copy code to Mac and build macOS .app bundle and DMG remotely
    vars:
      MAC_SRC: "~/mlcupscale_src"
    cmds:
      - |
        if [ "{{.MAC_HOST}}" = "user@remote-mac" ]; then
          echo "Error: MAC_HOST variable not set. Use 'MAC_HOST=user@host task build-macos-app'"
          exit 1
        fi
        echo "Syncing code to {{.MAC_HOST}}..."
        rsync -az --delete --exclude 'bin/' --exclude 'build/' --exclude '.git/' --exclude 'data/outputs/' --exclude 'data/uploads/' ./ {{.MAC_HOST}}:{{.MAC_SRC}}
        echo "Running build script on Mac..."
        ssh {{.MAC_HOST}} 'cd {{.MAC_SRC}}/deployments/macos && ./build-macos-app.sh'
    sources:
      - ./cmd/server/main.go
      - ./deployments/macos/Info.plist
      - ./deployments/macos/build-macos-app.sh
    generates:
      - '{{.MAC_SRC}}/../mlcupscale_build/MLCupscale.dmg'

  sync-macos:
    desc: Sync code to Mac without building
    vars:
      MAC_SRC: "~/mlcupscale_src"
    cmds:
      - |
        if [ "{{.MAC_HOST}}" = "user@remote-mac" ]; then
          echo "Error: MAC_HOST variable not set."
          exit 1
        fi
        rsync -az --delete --exclude 'bin/' --exclude 'build/' --exclude '.git/' --exclude 'data/outputs/' --exclude 'data/uploads/' ./ {{.MAC_HOST}}:{{.MAC_SRC}}

  start-macos-app:
    desc: Start the built application on the remote Mac
    cmds:
      - echo "Stopping existing instances..."
      - ssh {{.MAC_HOST}} 'pkill -f mlcupscale-bin || true'
      - echo "Starting MLCupscale.app on Mac..."
      - ssh {{.MAC_HOST}} 'open ~/mlcupscale_build/MLCupscale.app'

  stop-macos-app:
    desc: Stop the running application on the remote Mac
    cmds:
      - echo "Stopping MLCupscale on Mac..."
      - ssh {{.MAC_HOST}} 'pkill -f mlcupscale-bin || echo "No process found"'

  test-macos-health:
    desc: Test the health endpoint of the remote Mac service
    cmds:
      - echo "Checking health at http://{{.MAC_API_HOST}}:{{.MAC_API_PORT}}/api/v1/health..."
      - curl -f http://{{.MAC_API_HOST}}:{{.MAC_API_PORT}}/api/v1/health

  get-macos-logs:
    desc: Retrieve the application logs from the Mac
    cmds:
      - ssh {{.MAC_HOST}} 'tail -n 50 ~/Library/Logs/MLCupscale.log'

  test-macos-upscale:
    desc: Run a real upscale test against the Mac service with a tiny image
    cmds:
      - ./scripts/verify_upscale.sh {{.MAC_API_HOST}} {{.MAC_API_PORT}}

  verify-macos:
    desc: Build, Start, and Test the macOS deployment
    cmds:
      - task: build-macos-app
      - task: start-macos-app
      - cmd: sleep 5
      - task: test-macos-health
      - task: test-macos-upscale
